# Generated by Django 4.2.5 on 2023-11-20 07:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0023_alter_cycle_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='currently_renting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 13, 13, 19, 485687)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 13, 13, 19, 485687)),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('deposit_complete', models.BooleanField(default=False)),
                ('deposit_amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedal.appuser')),
            ],
        ),
    ]
