# Generated by Django 4.2.5 on 2023-11-19 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0029_alter_cycle_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='currently_renting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 23, 1, 34, 601369)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 23, 1, 34, 601369)),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 23, 1, 34, 601369)),
        ),
    ]
