# Generated by Django 4.2.5 on 2023-11-20 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0030_appuser_currently_renting_alter_cycle_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rating',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 12, 59, 504132)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 12, 59, 504132)),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 12, 59, 504132)),
        ),
    ]
